//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebModels.AccountResources", typeof(AccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressName.
        /// </summary>
        public static string AddressName {
            get {
                return ResourceManager.GetString("AddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên lái xe.
        /// </summary>
        public static string CarOwerName {
            get {
                return ResourceManager.GetString("CarOwerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarPartnerName.
        /// </summary>
        public static string CarPartnerName {
            get {
                return ResourceManager.GetString("CarPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangePrice.
        /// </summary>
        public static string ChangePrice {
            get {
                return ResourceManager.GetString("ChangePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestinationPartner.
        /// </summary>
        public static string DestinationPartner {
            get {
                return ResourceManager.GetString("DestinationPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistrictName.
        /// </summary>
        public static string DistrictName {
            get {
                return ResourceManager.GetString("DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is not a valid email address.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndLocation.
        /// </summary>
        public static string EndLocation {
            get {
                return ResourceManager.GetString("EndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not exist employee map vehicle.
        /// </summary>
        public static string ErrorEmployeeJoinVehicle {
            get {
                return ResourceManager.GetString("ErrorEmployeeJoinVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not exist vehicle map employee.
        /// </summary>
        public static string ErrorVeicleJoinEmployee {
            get {
                return ResourceManager.GetString("ErrorVeicleJoinEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want export exel file?.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FulllName {
            get {
                return ResourceManager.GetString("FulllName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationName.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationName Is Exists.
        /// </summary>
        public static string LocationNameExists {
            get {
                return ResourceManager.GetString("LocationNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect.
        /// </summary>
        public static string LoginIncorrect {
            get {
                return ResourceManager.GetString("LoginIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Not Valid.
        /// </summary>
        public static string MobileNotValid {
            get {
                return ResourceManager.GetString("MobileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add item, please check again!.
        /// </summary>
        public static string NotAdd {
            get {
                return ResourceManager.GetString("NotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t edit, please check!.
        /// </summary>
        public static string NotEdit {
            get {
                return ResourceManager.GetString("NotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BKS.
        /// </summary>
        public static string NumberPlate {
            get {
                return ResourceManager.GetString("NumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number plate already exists.
        /// </summary>
        public static string NumberPlateExists {
            get {
                return ResourceManager.GetString("NumberPlateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đối tác.
        /// </summary>
        public static string PartnerName {
            get {
                return ResourceManager.GetString("PartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partnername is  valid.
        /// </summary>
        public static string PartnerNameExists {
            get {
                return ResourceManager.GetString("PartnerNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan is exist.
        /// </summary>
        public static string PlanIsExist {
            get {
                return ResourceManager.GetString("PlanIsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is exists.
        /// </summary>
        public static string PriceIsExists {
            get {
                return ResourceManager.GetString("PriceIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is not saved.
        /// </summary>
        public static string PriceIsNotSaved {
            get {
                return ResourceManager.GetString("PriceIsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProvinceName.
        /// </summary>
        public static string ProvinceName {
            get {
                return ResourceManager.GetString("ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter  the AddressName.
        /// </summary>
        public static string RequiredAddressName {
            get {
                return ResourceManager.GetString("RequiredAddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter  the CarOwerName.
        /// </summary>
        public static string RequiredCarOwerName {
            get {
                return ResourceManager.GetString("RequiredCarOwerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter  the CarPartnerName.
        /// </summary>
        public static string RequiredCarPartnerName {
            get {
                return ResourceManager.GetString("RequiredCarPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Category.
        /// </summary>
        public static string RequiredCategory {
            get {
                return ResourceManager.GetString("RequiredCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Confirm Password.
        /// </summary>
        public static string RequiredConfirmPassword {
            get {
                return ResourceManager.GetString("RequiredConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Date.
        /// </summary>
        public static string RequiredDate {
            get {
                return ResourceManager.GetString("RequiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Destination Partner.
        /// </summary>
        public static string RequiredDestinationPartner {
            get {
                return ResourceManager.GetString("RequiredDestinationPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Driver.
        /// </summary>
        public static string RequiredDriver {
            get {
                return ResourceManager.GetString("RequiredDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required End Date.
        /// </summary>
        public static string RequiredEndDate {
            get {
                return ResourceManager.GetString("RequiredEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter  the EndLocation.
        /// </summary>
        public static string RequiredEndLocation {
            get {
                return ResourceManager.GetString("RequiredEndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requiredv End Time.
        /// </summary>
        public static string RequiredEndTime {
            get {
                return ResourceManager.GetString("RequiredEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredFulllName.
        /// </summary>
        public static string RequiredFulllName {
            get {
                return ResourceManager.GetString("RequiredFulllName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Km.
        /// </summary>
        public static string RequiredKm {
            get {
                return ResourceManager.GetString("RequiredKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter  the LocationName.
        /// </summary>
        public static string RequiredLocationName {
            get {
                return ResourceManager.GetString("RequiredLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter  the Mobile.
        /// </summary>
        public static string RequiredMobile {
            get {
                return ResourceManager.GetString("RequiredMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter  the NumberPlate.
        /// </summary>
        public static string RequiredNumberPlate {
            get {
                return ResourceManager.GetString("RequiredNumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Oil Level.
        /// </summary>
        public static string RequiredOilLevel {
            get {
                return ResourceManager.GetString("RequiredOilLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Oil Price.
        /// </summary>
        public static string RequiredOilPrice {
            get {
                return ResourceManager.GetString("RequiredOilPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Parking Price.
        /// </summary>
        public static string RequiredParkingPrice {
            get {
                return ResourceManager.GetString("RequiredParkingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter  the PartnerName.
        /// </summary>
        public static string RequiredPartnerName {
            get {
                return ResourceManager.GetString("RequiredPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Password.
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Pay Content.
        /// </summary>
        public static string RequiredPayContent {
            get {
                return ResourceManager.GetString("RequiredPayContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Pay Date.
        /// </summary>
        public static string RequiredPayDate {
            get {
                return ResourceManager.GetString("RequiredPayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Pay Price.
        /// </summary>
        public static string RequiredPayPrice {
            get {
                return ResourceManager.GetString("RequiredPayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose date.
        /// </summary>
        public static string RequiredPlanDate {
            get {
                return ResourceManager.GetString("RequiredPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Price.
        /// </summary>
        public static string RequiredPrice {
            get {
                return ResourceManager.GetString("RequiredPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Price Code.
        /// </summary>
        public static string RequiredPriceCode {
            get {
                return ResourceManager.GetString("RequiredPriceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Repair Category .
        /// </summary>
        public static string RequiredRepairCategory {
            get {
                return ResourceManager.GetString("RequiredRepairCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Repair Content.
        /// </summary>
        public static string RequiredRepairContent {
            get {
                return ResourceManager.GetString("RequiredRepairContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Repair Date.
        /// </summary>
        public static string RequiredRepairDate {
            get {
                return ResourceManager.GetString("RequiredRepairDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Repair Price.
        /// </summary>
        public static string RequiredRepairPrice {
            get {
                return ResourceManager.GetString("RequiredRepairPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Role Name.
        /// </summary>
        public static string RequiredRoleName {
            get {
                return ResourceManager.GetString("RequiredRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter  the RouteCode.
        /// </summary>
        public static string RequiredRouteCode {
            get {
                return ResourceManager.GetString("RequiredRouteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Source Partner.
        /// </summary>
        public static string RequiredSourcePartner {
            get {
                return ResourceManager.GetString("RequiredSourcePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Start Date.
        /// </summary>
        public static string RequiredStartDate {
            get {
                return ResourceManager.GetString("RequiredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter  the StartLocation.
        /// </summary>
        public static string RequiredStartLocation {
            get {
                return ResourceManager.GetString("RequiredStartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Start Time.
        /// </summary>
        public static string RequiredStartTime {
            get {
                return ResourceManager.GetString("RequiredStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Supplied Oil.
        /// </summary>
        public static string RequiredSuppliedOil {
            get {
                return ResourceManager.GetString("RequiredSuppliedOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter trip count.
        /// </summary>
        public static string RequiredTripCount {
            get {
                return ResourceManager.GetString("RequiredTripCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredUnitPrice.
        /// </summary>
        public static string RequiredUnitPrice {
            get {
                return ResourceManager.GetString("RequiredUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Username.
        /// </summary>
        public static string RequiredUserName {
            get {
                return ResourceManager.GetString("RequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose vehicle.
        /// </summary>
        public static string RequiredVehicle {
            get {
                return ResourceManager.GetString("RequiredVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Weight.
        /// </summary>
        public static string RequiredWeight {
            get {
                return ResourceManager.GetString("RequiredWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Description.
        /// </summary>
        public static string RoleDescription {
            get {
                return ResourceManager.GetString("RoleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already exists.
        /// </summary>
        public static string RoleExists {
            get {
                return ResourceManager.GetString("RoleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteCode.
        /// </summary>
        public static string RouteCode {
            get {
                return ResourceManager.GetString("RouteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteCode Is Exists.
        /// </summary>
        public static string RouteCodeExists {
            get {
                return ResourceManager.GetString("RouteCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in me.
        /// </summary>
        public static string SignInMe {
            get {
                return ResourceManager.GetString("SignInMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourcePartner.
        /// </summary>
        public static string SourcePartner {
            get {
                return ResourceManager.GetString("SourcePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartLocation.
        /// </summary>
        public static string StartLocation {
            get {
                return ResourceManager.GetString("StartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name already exists.
        /// </summary>
        public static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is not valid.
        /// </summary>
        public static string UserNameNotValid {
            get {
                return ResourceManager.GetString("UserNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải trọng.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightName.
        /// </summary>
        public static string WeightName {
            get {
                return ResourceManager.GetString("WeightName", resourceCulture);
            }
        }
    }
}
