//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebModels.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessAdminSites.
        /// </summary>
        public static string AccessAdminSites {
            get {
                return ResourceManager.GetString("AccessAdminSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessKey.
        /// </summary>
        public static string AccessKey {
            get {
                return ResourceManager.GetString("AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessLogs.
        /// </summary>
        public static string AccessLogs {
            get {
                return ResourceManager.GetString("AccessLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessWebModules.
        /// </summary>
        public static string AccessWebModules {
            get {
                return ResourceManager.GetString("AccessWebModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActualWeight.
        /// </summary>
        public static string ActualWeight {
            get {
                return ResourceManager.GetString("ActualWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressName.
        /// </summary>
        public static string AddressName {
            get {
                return ResourceManager.GetString("AddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminSite.
        /// </summary>
        public static string AdminSite {
            get {
                return ResourceManager.GetString("AdminSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Key.
        /// </summary>
        public static string AdminSiteAccessKey {
            get {
                return ResourceManager.GetString("AdminSiteAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AdminSiteDescription {
            get {
                return ResourceManager.GetString("AdminSiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site ID.
        /// </summary>
        public static string AdminSiteID {
            get {
                return ResourceManager.GetString("AdminSiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string AdminSiteParent {
            get {
                return ResourceManager.GetString("AdminSiteParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AdminSiteTitle {
            get {
                return ResourceManager.GetString("AdminSiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site URL.
        /// </summary>
        public static string AdminSiteUrl {
            get {
                return ResourceManager.GetString("AdminSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Costs.
        /// </summary>
        public static string AdvanceCosts {
            get {
                return ResourceManager.GetString("AdvanceCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport code.
        /// </summary>
        public static string AirportCode {
            get {
                return ResourceManager.GetString("AirportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport name.
        /// </summary>
        public static string AirportName {
            get {
                return ResourceManager.GetString("AirportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Oil.
        /// </summary>
        public static string AmountOil {
            get {
                return ResourceManager.GetString("AmountOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assizes.
        /// </summary>
        public static string Assizes {
            get {
                return ResourceManager.GetString("Assizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bday.
        /// </summary>
        public static string Bday {
            get {
                return ResourceManager.GetString("Bday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Costs.
        /// </summary>
        public static string BonusCosts {
            get {
                return ResourceManager.GetString("BonusCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chủ xe.
        /// </summary>
        public static string CarOwerName {
            get {
                return ResourceManager.GetString("CarOwerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarPartnerName.
        /// </summary>
        public static string CarPartnerName {
            get {
                return ResourceManager.GetString("CarPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangePrice.
        /// </summary>
        public static string ChangePrice {
            get {
                return ResourceManager.GetString("ChangePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Color.
        /// </summary>
        public static string CodeColor {
            get {
                return ResourceManager.GetString("CodeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentType.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentTypeID.
        /// </summary>
        public static string ContentTypeID {
            get {
                return ResourceManager.GetString("ContentTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country ID.
        /// </summary>
        public static string CountryID {
            get {
                return ResourceManager.GetString("CountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestinationPartner.
        /// </summary>
        public static string DestinationPartner {
            get {
                return ResourceManager.GetString("DestinationPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestinationPartnerID.
        /// </summary>
        public static string DestinationPartnerID {
            get {
                return ResourceManager.GetString("DestinationPartnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailCode.
        /// </summary>
        public static string DetailCode {
            get {
                return ResourceManager.GetString("DetailCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DifferenceOil.
        /// </summary>
        public static string DifferenceOil {
            get {
                return ResourceManager.GetString("DifferenceOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Price.
        /// </summary>
        public static string DistancePrice {
            get {
                return ResourceManager.GetString("DistancePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Total.
        /// </summary>
        public static string DistanceTotal {
            get {
                return ResourceManager.GetString("DistanceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistrictName.
        /// </summary>
        public static string DistrictName {
            get {
                return ResourceManager.GetString("DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string DriverID {
            get {
                return ResourceManager.GetString("DriverID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is not a valid email address.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndLocation.
        /// </summary>
        public static string EndLocation {
            get {
                return ResourceManager.GetString("EndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndLocationID.
        /// </summary>
        public static string EndLocationID {
            get {
                return ResourceManager.GetString("EndLocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndTime.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexLayout.
        /// </summary>
        public static string IndexLayout {
            get {
                return ResourceManager.GetString("IndexLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndexView.
        /// </summary>
        public static string IndexView {
            get {
                return ResourceManager.GetString("IndexView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Costs.
        /// </summary>
        public static string InsuranceCosts {
            get {
                return ResourceManager.GetString("InsuranceCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Code.
        /// </summary>
        public static string IsoCode {
            get {
                return ResourceManager.GetString("IsoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km.
        /// </summary>
        public static string Km {
            get {
                return ResourceManager.GetString("Km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link video.
        /// </summary>
        public static string LinkVideo {
            get {
                return ResourceManager.GetString("LinkVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationName.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Parent ID.
        /// </summary>
        public static string LocationParentID {
            get {
                return ResourceManager.GetString("LocationParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage.
        /// </summary>
        public static string Marriage {
            get {
                return ResourceManager.GetString("Marriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaDescription.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaKeywords.
        /// </summary>
        public static string MetaKeywords {
            get {
                return ResourceManager.GetString("MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaTitle.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Costs.
        /// </summary>
        public static string MortgageCosts {
            get {
                return ResourceManager.GetString("MortgageCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biển số xe.
        /// </summary>
        public static string NumberPlate {
            get {
                return ResourceManager.GetString("NumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Level.
        /// </summary>
        public static string OilLevel {
            get {
                return ResourceManager.GetString("OilLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Price.
        /// </summary>
        public static string OilPrice {
            get {
                return ResourceManager.GetString("OilPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Costs.
        /// </summary>
        public static string OtherCosts {
            get {
                return ResourceManager.GetString("OtherCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Name.
        /// </summary>
        public static string OtherName {
            get {
                return ResourceManager.GetString("OtherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Run.
        /// </summary>
        public static string OtherRun {
            get {
                return ResourceManager.GetString("OtherRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentAdminSite.
        /// </summary>
        public static string ParentAdminSite {
            get {
                return ResourceManager.GetString("ParentAdminSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentID.
        /// </summary>
        public static string ParentID {
            get {
                return ResourceManager.GetString("ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartnerCode.
        /// </summary>
        public static string PartnerCode {
            get {
                return ResourceManager.GetString("PartnerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartnerID.
        /// </summary>
        public static string PartnerID {
            get {
                return ResourceManager.GetString("PartnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đối tác.
        /// </summary>
        public static string PartnerName {
            get {
                return ResourceManager.GetString("PartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partnername is  valid.
        /// </summary>
        public static string PartnerNameExists {
            get {
                return ResourceManager.GetString("PartnerNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Content.
        /// </summary>
        public static string PayContent {
            get {
                return ResourceManager.GetString("PayContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Costs.
        /// </summary>
        public static string PhoneCosts {
            get {
                return ResourceManager.GetString("PhoneCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanDate.
        /// </summary>
        public static string PlanDate {
            get {
                return ResourceManager.GetString("PlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Info.
        /// </summary>
        public static string PriceInfo {
            get {
                return ResourceManager.GetString("PriceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Of Driver.
        /// </summary>
        public static string PriceOfDriver {
            get {
                return ResourceManager.GetString("PriceOfDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Of Parking.
        /// </summary>
        public static string PriceOfParking {
            get {
                return ResourceManager.GetString("PriceOfParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Old.
        /// </summary>
        public static string PriceOld {
            get {
                return ResourceManager.GetString("PriceOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProvinceName.
        /// </summary>
        public static string ProvinceName {
            get {
                return ResourceManager.GetString("ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishDetailLayout.
        /// </summary>
        public static string PublishDetailLayout {
            get {
                return ResourceManager.GetString("PublishDetailLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishDetailView.
        /// </summary>
        public static string PublishDetailView {
            get {
                return ResourceManager.GetString("PublishDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishIndexLayout.
        /// </summary>
        public static string PublishIndexLayout {
            get {
                return ResourceManager.GetString("PublishIndexLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishIndexView.
        /// </summary>
        public static string PublishIndexView {
            get {
                return ResourceManager.GetString("PublishIndexView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Category .
        /// </summary>
        public static string RepairCategory {
            get {
                return ResourceManager.GetString("RepairCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Content .
        /// </summary>
        public static string RepairContent {
            get {
                return ResourceManager.GetString("RepairContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Title.
        /// </summary>
        public static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement enter the Username.
        /// </summary>
        public static string RequiredUserName {
            get {
                return ResourceManager.GetString("RequiredUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RouteCode.
        /// </summary>
        public static string RouteCode {
            get {
                return ResourceManager.GetString("RouteCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Total.
        /// </summary>
        public static string SalaryTotal {
            get {
                return ResourceManager.GetString("SalaryTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeoTitle.
        /// </summary>
        public static string SeoTitle {
            get {
                return ResourceManager.GetString("SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string Skype {
            get {
                return ResourceManager.GetString("Skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourcePartner.
        /// </summary>
        public static string SourcePartner {
            get {
                return ResourceManager.GetString("SourcePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourcePartnerID.
        /// </summary>
        public static string SourcePartnerID {
            get {
                return ResourceManager.GetString("SourcePartnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartLocation.
        /// </summary>
        public static string StartLocation {
            get {
                return ResourceManager.GetString("StartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartLocationID.
        /// </summary>
        public static string StartLocationID {
            get {
                return ResourceManager.GetString("StartLocationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAdminSites.
        /// </summary>
        public static string SubAdminSites {
            get {
                return ResourceManager.GetString("SubAdminSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubQuerys.
        /// </summary>
        public static string SubQuerys {
            get {
                return ResourceManager.GetString("SubQuerys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubWebModules.
        /// </summary>
        public static string SubWebModules {
            get {
                return ResourceManager.GetString("SubWebModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied From Level.
        /// </summary>
        public static string SuppliedFromLevel {
            get {
                return ResourceManager.GetString("SuppliedFromLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuppliedOil.
        /// </summary>
        public static string SuppliedOil {
            get {
                return ResourceManager.GetString("SuppliedOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Costs.
        /// </summary>
        public static string SupportCosts {
            get {
                return ResourceManager.GetString("SupportCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Date Ticket.
        /// </summary>
        public static string TotalDateTicket {
            get {
                return ResourceManager.GetString("TotalDateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Driver Pay.
        /// </summary>
        public static string TotalDriverPay {
            get {
                return ResourceManager.GetString("TotalDriverPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalMoney.
        /// </summary>
        public static string TotalMoney {
            get {
                return ResourceManager.GetString("TotalMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Month Ticket.
        /// </summary>
        public static string TotalMonthTicket {
            get {
                return ResourceManager.GetString("TotalMonthTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Oil.
        /// </summary>
        public static string TotalOil {
            get {
                return ResourceManager.GetString("TotalOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Parking.
        /// </summary>
        public static string TotalParking {
            get {
                return ResourceManager.GetString("TotalParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Repair Vehicle.
        /// </summary>
        public static string TotalRepairVehicle {
            get {
                return ResourceManager.GetString("TotalRepairVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Salary.
        /// </summary>
        public static string TotalSalary {
            get {
                return ResourceManager.GetString("TotalSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Transport Actual.
        /// </summary>
        public static string TotalTransportActual {
            get {
                return ResourceManager.GetString("TotalTransportActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackingCode.
        /// </summary>
        public static string TrackingCode {
            get {
                return ResourceManager.GetString("TrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Back.
        /// </summary>
        public static string TripBack {
            get {
                return ResourceManager.GetString("TripBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripCount.
        /// </summary>
        public static string TripCount {
            get {
                return ResourceManager.GetString("TripCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        public static string UID {
            get {
                return ResourceManager.GetString("UID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitPrice.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is not valid.
        /// </summary>
        public static string UserNameNotValid {
            get {
                return ResourceManager.GetString("UserNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleID.
        /// </summary>
        public static string VehicleID {
            get {
                return ResourceManager.GetString("VehicleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleWeight.
        /// </summary>
        public static string VehicleWeight {
            get {
                return ResourceManager.GetString("VehicleWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web CategoryID.
        /// </summary>
        public static string WebCategoryID {
            get {
                return ResourceManager.GetString("WebCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebContacts.
        /// </summary>
        public static string WebContacts {
            get {
                return ResourceManager.GetString("WebContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Content ID.
        /// </summary>
        public static string WebContentID {
            get {
                return ResourceManager.GetString("WebContentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebContents.
        /// </summary>
        public static string WebContents {
            get {
                return ResourceManager.GetString("WebContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebModule.
        /// </summary>
        public static string WebModule {
            get {
                return ResourceManager.GetString("WebModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebModuleID.
        /// </summary>
        public static string WebModuleID {
            get {
                return ResourceManager.GetString("WebModuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải trọng.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightID.
        /// </summary>
        public static string WeightID {
            get {
                return ResourceManager.GetString("WeightID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightName.
        /// </summary>
        public static string WeightName {
            get {
                return ResourceManager.GetString("WeightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Day.
        /// </summary>
        public static string WorkDay {
            get {
                return ResourceManager.GetString("WorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Day Price.
        /// </summary>
        public static string WorkDayPrice {
            get {
                return ResourceManager.GetString("WorkDayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Day Total.
        /// </summary>
        public static string WorkDayTotal {
            get {
                return ResourceManager.GetString("WorkDayTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo.
        /// </summary>
        public static string Yahoo {
            get {
                return ResourceManager.GetString("Yahoo", resourceCulture);
            }
        }
    }
}
